In [1]:
import numpy as np
import pandas as pd
import xarray as xr
from pathlib import Path
import pygrib
from pathlib import Path

In [2]:
dir = Path("/mnt/data/output/gfs_indo/2021/01")
data = xr.open_dataset(dir / "gfs_20210101_0000.nc")

In [3]:
datag

<xarray.Dataset>
Dimensions:  (lat: 261, level: 13, lon: 401, time: 33)
Coordinates:
  * time     (time) datetime64[ns] 2021-01-01 2021-01-01T03:00:00 ... 2021-01-05
  * lon      (lon) float64 70.0 70.25 70.5 70.75 ... 169.2 169.5 169.8 170.0
  * lat      (lat) float64 -25.0 -24.75 -24.5 -24.25 ... 39.25 39.5 39.75 40.0
  * level    (level) float64 1e+03 950.0 925.0 900.0 ... 400.0 300.0 250.0 200.0
Data variables:
    rr       (time, lat, lon) float32 ...
    li       (time, lat, lon) float32 ...
    cape     (time, lat, lon) float32 ...
    mslp     (time, lat, lon) float32 ...
    tcc      (time, lat, lon) float32 ...
    u10      (time, lat, lon) float32 ...
    v10      (time, lat, lon) float32 ...
    dp2      (time, lat, lon) float32 ...
    rh2      (time, lat, lon) float32 ...
    t2       (time, lat, lon) float32 ...
    u        (time, level, lat, lon) float32 ...
    v        (time, level, lat, lon) float32 ...
    w        (time, level, lat, lon) float32 ...
    rh       (time, level, lat, lon) float32 ...
    t        (time, level, lat, lon) float32 ...
    absv     (time, level, lat, lon) float32 ...
    tp       (time, lat, lon) float32 ...
    tp24     (time, lat, lon) float32 ...
    dp       (time, level, lat, lon) float32 ...
    ki       (time, lat, lon) float32 ...
    tt       (time, lat, lon) float32 ...
    si       (time, lat, lon) float32 ...
    fl       (time, lat, lon) float32 ...
    cb       (time, lat, lon) float32 ...
Attributes:
    ordinal:  737791

<xarray.DataArray 't' (lon: 401)>
array([20.440723, 20.440723, 20.440723, ..., 22.040722, 22.340723, 22.340723],
      dtype=float32)
Coordinates:
    time     datetime64[ns] 2021-01-01
  * lon      (lon) float64 70.0 70.25 70.5 70.75 ... 169.2 169.5 169.8 170.0
    lat      float64 -25.0
    level    float64 1e+03
Attributes:
    long_name:  Temperature
    units:      degC

In [4]:
grbs = pygrib.open("gfsdowntemp/20231127/t00/t00.f001")

In [2]:
a = Path('/mnt/data/output/gfs_indo_v2/2023/11')

In [3]:
ds = xr.open_dataset(str(a)+'/gfs_20231127_0000.nc')

In [4]:
ds

<xarray.Dataset>
Dimensions:          (lat: 69, level: 16, lon: 185, time: 10)
Coordinates:
  * lon              (lon) float64 95.0 95.25 95.5 95.75 ... 140.5 140.8 141.0
  * lat              (lat) float64 -11.0 -10.75 -10.5 -10.25 ... 5.5 5.75 6.0
  * level            (level) float64 0.0 100.0 150.0 200.0 ... 925.0 950.0 1e+03
  * time             (time) datetime64[ns] 2023-11-27T01:00:00 ... 2023-11-27...
Data variables:
    rh2              (time, lat, lon) float64 ...
    t2               (time, lat, lon) float64 ...
    u10              (time, lat, lon) float64 ...
    v10              (time, lat, lon) float64 ...
    vis              (time, lat, lon) float64 ...
    gust             (time, lat, lon) float64 ...
    prate            (time, lat, lon) float64 ...
    rr               (time, lat, lon) float64 ...
    lftx             (time, lat, lon) float64 ...
    cape             (time, lat, lon) float64 ...
    tcc_atmospheric  (time, lat, lon) float64 ...
    u                (time, level, lat, lon) float64 ...
    v                (time, level, lat, lon) float64 ...
    gh               (time, level, lat, lon) float64 ...
    t                (time, level, lat, lon) float64 ...
    r                (time, level, lat, lon) float64 ...
    tcc_isobaric     (time, level, lat, lon) float64 ...

In [5]:
ds['tcc_atmospheric'][8,:,:]

<xarray.DataArray 'tcc_atmospheric' (lat: 69, lon: 185)>
array([[100. , 100. , 100. , ...,  18.7,  41.1, 100. ],
       [100. , 100. , 100. , ...,  41.1,  69.1, 100. ],
       [100. , 100. , 100. , ...,  99.8, 100. , 100. ],
       ...,
       [100. , 100. , 100. , ...,  37.9, 100. , 100. ],
       [100. , 100. , 100. , ...,  86.1,  78.8, 100. ],
       [ 97.3, 100. , 100. , ..., 100. ,  34.9, 100. ]])
Coordinates:
  * lon      (lon) float64 95.0 95.25 95.5 95.75 ... 140.2 140.5 140.8 141.0
  * lat      (lat) float64 -11.0 -10.75 -10.5 -10.25 -10.0 ... 5.25 5.5 5.75 6.0
    time     datetime64[ns] 2023-11-27T09:00:00

In [11]:
ds['tcc_isobaric'][2,4,:,:]

<xarray.DataArray 'tcc_isobaric' (lat: 69, lon: 185)>
array([[  0. ,   0. ,   0. , ...,   0. ,   0. ,   0. ],
       [  0. ,   0. ,   2.7, ...,   0. ,   0. ,   0. ],
       [  0. ,   0. ,   0. , ...,   0. ,   0. ,   0. ],
       ...,
       [ 21.3,  36.3,   5.2, ...,   0. ,   0. ,   0. ],
       [ 25.5,  94.5,  69.8, ...,   0. ,   0. ,   0. ],
       [ 45.6,  74.9, 100. , ...,   0. ,   0. ,   0. ]])
Coordinates:
  * lon      (lon) float64 95.0 95.25 95.5 95.75 ... 140.2 140.5 140.8 141.0
  * lat      (lat) float64 -11.0 -10.75 -10.5 -10.25 -10.0 ... 5.25 5.5 5.75 6.0
    level    float64 250.0
    time     datetime64[ns] 2023-11-27T03:00:00